
import Head from 'next/head';
import Footer from '../components/Footer/Footer';
import Header from '../components/Header/Header';

const HomePage: React.FC = () => {
	return (
		<div>
			<Head>
				<title>Hypescout: Home Page</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/assets/images/icon/fav.png" />
			</Head>
			<Header />
			<Footer />
		</div>
	)
}

export default HomePage;
